"""Cleaning + SQL + statistics + charts on music_trends_data.csv. Run: python analysis.py"""
import re, sqlite3
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd
from scipy import stats

df = pd.read_csv("music_trends_data.csv")

# ---- 1. Cleaning ----
print(f"Rows: {len(df)} | missing values per column: {df.isnull().sum().to_dict()}")
print(f"Duplicate track names: {df.track_name.duplicated().sum()} | year range: {df.year.min()} to {df.year.max()}")
df["primary_genre"] = df.genre.str.split("/").str[0].str.strip()      # 'EDM/Pop' -> 'EDM'
df["decade"] = (df.year // 10) * 10
print(f"Genre labels: {df.genre.nunique()} raw -> {df.primary_genre.nunique()} after taking the primary genre")

con = sqlite3.connect(":memory:")
df.to_sql("tracks", con, index=False)

summary = ["# Music Trends analysis summary (generated by analysis.py)\n"]

# ---- 2. SQL analysis ----
sql = open("music_queries.sql").read()
for name, q in re.findall(r"-- name: (\w+)[^\n]*\n(.*?)(?=-- name:|\Z)", sql, flags=re.S):
    res = pd.read_sql_query(q, con)
    res.to_csv(f"{name}.csv", index=False)
    print(f"\n=== {name} ===\n{res.to_string(index=False)}")
    summary.append(f"## {name}\n```\n{res.to_string(index=False)}\n```\n")

# ---- 3. Statistics ----
print("\n=== STATISTICS ===")
lines = []
groups = [g.popularity.values for _, g in df.groupby("platform") if len(g) >= 5]
f, p = stats.f_oneway(*groups)
lines.append(f"One-way ANOVA, popularity across platforms: F={f:.2f}, p={p:.3f}")
h, p = stats.kruskal(*groups)
lines.append(f"Kruskal-Wallis, popularity across platforms: H={h:.2f}, p={p:.3f}")
rho, p = stats.spearmanr(df.tempo, df.popularity)
lines.append(f"Spearman, tempo vs popularity: rho={rho:.2f}, p={p:.3f}")
rho, p = stats.spearmanr(df.year, df.popularity)
lines.append(f"Spearman, release year vs popularity: rho={rho:.2f}, p={p:.3f}")
mid = df[(df.tempo >= 90) & (df.tempo <= 110)].popularity
rest = df[(df.tempo < 90) | (df.tempo > 110)].popularity
t, p = stats.ttest_ind(mid, rest, equal_var=False)
lines.append(f"Welch t-test, mid-tempo (90-110 BPM) vs other tracks: means {mid.mean():.2f} vs {rest.mean():.2f}, t={t:.2f}, p={p:.3f}")
u, p = stats.mannwhitneyu(mid, rest)
lines.append(f"Mann-Whitney U, mid-tempo vs other tracks: p={p:.3f}")
d2 = df[df.track_name != "Beatbox Battle"]            # lowest-popularity outlier (70)
mid2 = d2[(d2.tempo >= 90) & (d2.tempo <= 110)].popularity
rest2 = d2[(d2.tempo < 90) | (d2.tempo > 110)].popularity
t, p = stats.ttest_ind(mid2, rest2, equal_var=False)
lines.append(f"Same t-test without the outlier track 'Beatbox Battle': means {mid2.mean():.2f} vs {rest2.mean():.2f}, p={p:.3f}")
lines.append(f"Popularity range in the data: {df.popularity.min()} to {df.popularity.max()} (mean {df.popularity.mean():.1f}, sd {df.popularity.std():.1f})")
lines.append("Rule: p < 0.05 = statistically significant.")
print("\n".join(lines))
summary.append("## Statistical tests\n```\n" + "\n".join(lines) + "\n```\n")

# ---- 4. Charts ----
df.primary_genre.value_counts().head(10).sort_values().plot.barh(title="Top 10 genres by track count")
plt.savefig("top_genres.png", dpi=150, bbox_inches="tight"); plt.clf()
plt.scatter(df.tempo, df.popularity, alpha=0.6)
plt.xlabel("Tempo (BPM)"); plt.ylabel("Popularity"); plt.title("Tempo vs popularity")
plt.savefig("tempo_vs_popularity.png", dpi=150, bbox_inches="tight"); plt.clf()
df.groupby("platform").popularity.mean().sort_values().plot.barh(title="Average popularity by platform")
plt.savefig("platform_popularity.png", dpi=150, bbox_inches="tight")

open("analysis_summary.md", "w").write("\n".join(summary))
print("\nSaved result CSVs, charts and analysis_summary.md")
